apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-agent
  namespace: teamcity
  labels:
    app: teamcity-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcity-agent
  template:
    metadata:
      name: teamcity-agent
      labels:
        app: teamcity-agent
    spec:
      containers:
        - name: teamcity-agent
          image: jetbrains/teamcity-agent
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: SERVER_URL
              value: http://teamcity-server:8111
            - name: AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath:  metadata.name
      restartPolicy: Always
