apiVersion: v1
kind: Service
metadata:
  name: teamcity-agent
  namespace: teamcity
spec:
  selector:
    app: teamcity-agent
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP