apiVersion: v1
kind: Service
metadata:
  name: teamcity-server
  namespace: teamcity
spec:
  selector:
    app: teamcity-server
  ports:
    - protocol: TCP
      port: 8111
      targetPort: 8111
  type: LoadBalancer